###login: testuser,1q2w3e, test@test.com, sleep
POST http://localhost:8080/user/login
Content-Type: application/json
Accept: : application/json

{
  "id": "testuser",
  "password": "1q2w3e"
}

###redis: testuser,1q2w3e, test@test.com, sleep
POST http://localhost:8080/user/login.test
Content-Type: application/json
Accept: : application/json

{
  "id": "testuser",
  "password": "1q2w3e"
}


###create: testuser2, 1q2w3e4r, test2@test.com, active
POST http://localhost:8080/user/signup
Content-Type: application/json
Accept: : application/json

{
  "id": "testuser2",
  "email": "test2@test.com",
  "password": "1q2w3e4r"
}

###delete: testuser2, 1q2w3e4r, test2@test.com, active
DELETE http://localhost:8080/user/withdraw
Content-Type: application/json
Accept: application/json

{
  "id": "testuser2",
  "password": "1q2w3e4r"
}